pip install scapy
sudo apt-get update
sudo apt-get install nmap
pip install python-nmap
pip install multiprocessing
pip install scapy
pip install opencv-python
pip install requests
pip install lxml
pip install beautifulsoup4
pip install github3.py
pip install base64
pip install importlib
pip install json
pip install random
pip install sys
pip install threading
pip install time
pip install datetime
pip install python-magic
pip install pythoncom
pip install pyWinhook
pip install psutil
pip install pynput
pip install ctypes
pip install os
pip install platform
pip install time
pip install pywin32
pip install python3-xlib
pip install argsparce
pip install pycryptodomex
pip install smtplib
pip install pywin32
pip install ftplib
pip install flask
